version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: templatesdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./Api
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=templatesdb;Username=postgres;Password=postgres"
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5276:80"
    restart: on-failure

volumes:
  db-data: